spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bancking_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret-key: e7918a5ed84f1c35da180cadc375efa01bd50323f27b747bd6b802cefa48f487
    expiration : 60000
    refreshTokenDurationMs: 180000
